---
- name: Install python3, docker 
  hosts: tag_Name_dev_server
  become: True
  tasks:
    - name: Make sure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: True
        state: present

- name: Downgrade urllib3 version
  hosts: tag_Name_dev_server
  become: True
  tasks:
    - name: Uninstall the existing urllib3 package
      pip:
        name: urllib3
        state: absent

    - name: Install urllib3 version 1.26.7
      pip:
        name: urllib3==1.26.7

- name: Install docker-compose
  hosts: tag_Name_dev_server
  become: True
  tasks:
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start docker deamon
  hosts: tag_Name_dev_server
  become: True
  tasks:
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started

- name: Install docker and docker-compose python module
  hosts: tag_Name_dev_server
  become: True
  tasks:
      - name: Install docker python module
        pip:
          name:
            - docker
            - docker-compose

- name: Add ec2 user to docker group
  hosts: tag_Name_dev_server
  become: True
  tasks:
    - name: Add ec2 user to docker group
      user:
        name: ec2-user
        groups: docker
        append: True
    - name: Reconnect to server session
      meta: reset_connection
        
- name: Test docker pull
  hosts: tag_Name_dev_server
  tasks:
    - name: Pull redis image
      docker_image:
        name: redis
        source: pull

- name: Start docker containers
  hosts: tag_Name_dev_server
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /home/jayce/ansible/docker-deployment-ec2-instance/docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: "{{ lookup('env', 'DOCKER_REGISTRY') }}"
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present # docker-compose up
